"""共享调参常量：SRS、计划分配和上下文阈值。"""

# 计划相关脚本默认按“今天该先学什么”的主攻顺序排优先级。
PLAN_SUBJECTS = ("数学一", "408", "英语一", "政治")

# 成绩、目标分和模考相关脚本保持正式分数栏位顺序。
SCORE_SUBJECTS = ("政治", "数学一", "英语一", "408")

SRS_DEFAULT_EASE_FACTOR = 2.5
SRS_EASE_PENALTY_FACTOR = 0.8
SRS_EASE_FLOOR = 1.3
SRS_EASE_REWARD_STEP = 0.1
SRS_HALF_KNOWN_INTERVAL_MULTIPLIER = 1.2
SRS_GRADUATED_INTERVAL_DAYS = 90
SRS_OVERDUE_DEGRADE_DAYS = 7

DAILY_PLAN_DUE_LIMIT = 10
DAILY_PLAN_REVIEW_HOURS_RATIO = 0.4
DAILY_PLAN_CARD_HOURS = 0.25
DAILY_PLAN_MIN_REVIEW_TRIGGER_HOURS = 1.5
DAILY_PLAN_MIN_REVIEW_HOURS = 0.5
DAILY_PLAN_PRIMARY_SUBJECT_SHARE = 0.6
DAILY_PLAN_PROGRESS_WRAPUP_MINUTES = 10

WEEKLY_PLAN_FOCUS_WEIGHT = 1.4
WEEKLY_PLAN_DUE_WEIGHT = 0.8
WEEKLY_PLAN_DUE_WEIGHT_CAP = 5

LOAD_DUE_BACKLOG_WARNING_THRESHOLD = 10
LOAD_COUNTDOWN_WINDOW_DAYS = 100

LEGACY_HEADING_INDENT_LIMIT = 200

# scan_due_reviews.py 中题目预览的最大行数。
QUESTION_PREVIEW_LINE_LIMIT = 3
